### ISSUE TITLE
Example "BasicUsage" does not compile

### ISSUE THREAD

**Issue by ttttttom** [WifWaf/TCA9548A#10]
Arduino IDE Version 1.8.3
TCA9548A.h Version 1.1.1

It does not compile, but as it is an example, it should?!

**Comment by WifWaf** [comment]
Need a bit more information. 

Can you copy the error message(s), and the MCU you are using?

Also - do you mean IDE version 1.8.13?

**Comment by ttttttom** [comment]
IDE Version 1.8.13
Arduino Nano, Arduino Uno.

Messages:

Arduino: 1.8.13 (Linux), Board: "Arduino Nano, ATmega328P (Old Bootloader)"

/home/to/sciebo/TT_Arduino/libraries/TCA9548A/src/TCA9548A.cpp: In member function 'uint8_t TCA9548A::read()':
/home/to/sciebo/TT_Arduino/libraries/TCA9548A/src/TCA9548A.cpp:84:73: error: call of overloaded 'requestFrom(uint16_t, uint8_t, bool)' is ambiguous
     this->myWire->requestFrom((uint16_t)this->_address, (uint8_t)1, true);
                                                                         ^
In file included from /home/to/sciebo/TT_Arduino/libraries/TCA9548A/src/TCA9548A.h:13:0,
                 from /home/to/sciebo/TT_Arduino/libraries/TCA9548A/src/TCA9548A.cpp:9:
/home/to/Downloads/arduino-1.8.13/hardware/arduino/avr/libraries/Wire/src/Wire.h:66:13: note: candidate: uint8_t TwoWire::requestFrom(uint8_t, uint8_t, uint8_t)
     uint8_t requestFrom(uint8_t, uint8_t, uint8_t);
             ^~~~~~~~~~~
/home/to/Downloads/arduino-1.8.13/hardware/arduino/avr/libraries/Wire/src/Wire.h:69:13: note: candidate: uint8_t TwoWire::requestFrom(int, int, int)
     uint8_t requestFrom(int, int, int);
             ^~~~~~~~~~~
exit status 1
Fehler beim Kompilieren für das Board Arduino Nano.

Dieser Bericht wäre detaillierter, wenn die Option
"Ausführliche Ausgabe während der Kompilierung"
in Datei -> Voreinstellungen aktiviert wäre.

**Comment by WifWaf** [comment]
Cheers, 

This is an issue fixed last month.  I've been having trouble getting the library manager to update the code - will try again.

If you replace your local library files TCA9548A.h and TCA9548A.cpp , with their equivalents in the src directory here, it should fix the issue.

Essentially it's due to changes in the Wire library which vary between MCUs and their respective Arduino cores - It's not sure which function to call.

**Comment by ttttttom** [comment]
Ok, thanks for your help and solution :-)

**Comment by WifWaf** [comment]
No worries - hopefully, it, will update automatically in future :)

I will close this issue for now. Just re-open/comment if no luck.
