### ISSUE TITLE
Cannot assign different SCL/SDA pins

### ISSUE THREAD

**Issue by thijstriemstra** [WifWaf/TCA9548A#5]
the `begin()` method accepts a TwoWire instance and then calls `begin()` on that instance:

https://github.com/WifWaf/TCA9548A/blob/master/src/TCA9548A.cpp#L15

Instead it should call `twowire.begin(sda, scl)`. Or this library should not call `begin()` on the instance and let the user do this (so the custom sda/scl pins can be passed then).

I made this change to `begin` and now it works:

```cpp
void TCA9548A::begin(TwoWire &inWire, int sda_pin, int scl_pin)
{
    this->myWire = &inWire;
    this->myWire->begin(sda_pin, scl_pin);
}
```

**Comment by WifWaf** [comment]
It was removed here 5fbbedbe326e2c2a5096e7ac49634df240389b16

If I remember correctly... the arguments were removed as the UNO will not compile. It has a single hardware I2C port and doesn't have an overload function for specifying which pins you want to use. 

I think new Arduino users tend to get confused/forget and in sketches and so it causes problems/issues to be raised.

Not sure on your device, however, the[ESP32 can take a setpin argument](https://github.com/espressif/arduino-esp32/blob/4d98cea085d619bed7026b37071bd8402a485d95/libraries/Wire/src/Wire.cpp#L61) which should allow this to work without changing the begin function.

Perhaps adding preprocessor directives to switch the function out for the UNO would be the best solution (unless there's something more obvious).

**Comment by thijstriemstra** [comment]
> If I remember correctly... the arguments were removed as the UNO will not compile.

Ok, if there's an exception for the Uno I agree "adding preprocessor directives" sounds like a good thing to do. But I haven't encountered any differences, or compile errors between Uno/Nano/ESP32 using TwoWire.

> Not sure on your device, however, theESP32 can take a setpin argument which should allow this to work without changing the begin function.

Never heard of that before, sounds like an obscure option..

**Comment by thijstriemstra** [comment]
> Or this library should not call begin() on the instance and let the user do this (so the custom sda/scl pins can be passed then).

This is also an option of course. Users would have to call `begin` on their TwoWire instance themselves.

**Comment by WifWaf** [comment]
[See here for the *ArduinoCore begin functions](https://github.com/arduino/ArduinoCore-avr/blob/master/libraries/Wire/src/Wire.cpp).

From what I can see, any library using the official ArduinoCore will not compile with a begin(sda, sdl) type function - I've double-checked this on a UNO and MEGA for sanity.

> This is also an option of course. Users would have to call begin on their TwoWire instance themselves.

I think this would cause confusion as it's not convention as it's usually always unnecessary. To be honest, I suspect this is why the ESP32 has a setpin function. 

It might actually be best to include a comment in the example to show the workaround setpin function.  *excuse the spelling errors

**Comment by thijstriemstra** [comment]
> I think this would cause confusion as it's not convention as it's usually always unnecessary. 

Not sure, when using TwoWire I expect to do some extra work myself, so I wouldn't mind.

>  It might actually be best to include a comment in the example to show the workaround setpin function. *excuse the spelling errors

Looking forward to a workaround. Until then I'll use my fork with platformio:

```ini
lib_deps =
  ; use wire fixes, see https://github.com/WifWaf/TCA9548A/issues/5
  https://github.com/thijstriemstra/TCA9548A.git#twowire-5
```

**Comment by WifWaf** [comment]
Yea - I get you.

[The setPins is recen](https://github.com/espressif/arduino-esp32/commit/4d98cea085d619bed7026b37071bd8402a485d95#diff-ce3a2c7e492f1564fb18ca795f409119)t, so yes, work with your fork. 

I'll add this to relevant repository examples once it's in the stable arduino-esp32 branch.

I'll keep this issue open until then.

**Comment by thijstriemstra** [comment]
Ah nice find, that's a good addition to arduino-esp32.

**Comment by thijstriemstra** [comment]
@WifWaf I just upgraded to Espressif 32 2.0, does this mean `setPins`'s available now?

**Comment by WifWaf** [comment]
It wasn't included in the [stable 1.0.4 release yesterday](https://github.com/espressif/arduino-esp32/releases/tag/1.0.4) (I think this is 2.0 on PIO) .. for some reason.

It is still in the master branch and looks like [Adafruit are waiting ](https://github.com/espressif/arduino-esp32/issues/3779) for it as well - so hopefully in the next one?

**Comment by WifWaf** [comment]
[It's been included in today's pre-release](https://github.com/espressif/arduino-esp32/blob/be4d3b6cb87236a749a0abc8288b49cb6b79710b/libraries/Wire/src/Wire.cpp#L61). Once it's out of pre-release and PIO update their version - I'll add the changes.

Good times.

**Comment by WifWaf** [comment]
setPins has been added to the examples due to the recent update - it should be usable on PIO very soon.

**Comment by thijstriemstra** [comment]
> to the recent update 

What specific version?

**Comment by WifWaf** [comment]
I was going to say 1.0.5, but [checking the json file I'm using, it seems it's still 1.0.4](https://raw.githubusercontent.com/espressif/arduino-esp32/gh-pages/package_esp32_index.json). 

Would you mind checking if your Arduino IDE compiles Wire.setPins(sda, scl)?

Seems I might an issue with my Arduino IDE... *rather than the update finally being available.

**Comment by thijstriemstra** [comment]
I don't use Arduino IDE, I'll give it a try with PlatformIO.

**Comment by thijstriemstra** [comment]
Not yet... 

<img width="520" alt="Screenshot 2020-12-27 at 20 46 26" src="https://user-images.githubusercontent.com/305679/103178625-a79e8980-4884-11eb-8e07-f19996b76777.png">

Using espressif 32 2.1.0

**Comment by WifWaf** [comment]
I guess I installed a development version previously which is causing issues. How ironic, I only use Arduino IDE for testing library compatibility.

I'll wait on PIO for versioning in future - cheers for the verification.

**Comment by WifWaf** [comment]
I believe this is resolved now with the latest version of Arduino ESP32?

**Comment by thijstriemstra** [comment]
Looks like it!

```c++
public:
    TwoWire(uint8_t bus_num);
    ~TwoWire();
    
    //call setPins() first, so that begin() can be called without arguments from libraries
    bool setPins(int sda, int scl);
```
